/**
 * TextMagic API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * Contact: support@textmagi.biz
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.8.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "CreatePushTokenInputObject.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

CreatePushTokenInputObject::CreatePushTokenInputObject()
{
    m_DeviceId = utility::conversions::to_string_t("");
    m_PushServiceType = utility::conversions::to_string_t("");
}

CreatePushTokenInputObject::~CreatePushTokenInputObject()
{
}

void CreatePushTokenInputObject::validate()
{
    // TODO: implement validation
}

web::json::value CreatePushTokenInputObject::toJson() const
{
    web::json::value val = web::json::value::object();

    val[utility::conversions::to_string_t("deviceId")] = ModelBase::toJson(m_DeviceId);
    val[utility::conversions::to_string_t("pushServiceType")] = ModelBase::toJson(m_PushServiceType);

    return val;
}

void CreatePushTokenInputObject::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("deviceId")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("deviceId")];
        if(!fieldValue.is_null())
        {
            setDeviceId(ModelBase::stringFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("pushServiceType")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("pushServiceType")];
        if(!fieldValue.is_null())
        {
            setPushServiceType(ModelBase::stringFromJson(fieldValue));
        }
    }
}

void CreatePushTokenInputObject::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("deviceId"), m_DeviceId));
    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("pushServiceType"), m_PushServiceType));
}

void CreatePushTokenInputObject::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    setDeviceId(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("deviceId"))));
    setPushServiceType(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("pushServiceType"))));
}

utility::string_t CreatePushTokenInputObject::getDeviceId() const
{
    return m_DeviceId;
}


void CreatePushTokenInputObject::setDeviceId(utility::string_t value)
{
    m_DeviceId = value;
    
}
utility::string_t CreatePushTokenInputObject::getPushServiceType() const
{
    return m_PushServiceType;
}


void CreatePushTokenInputObject::setPushServiceType(utility::string_t value)
{
    m_PushServiceType = value;
    
}
}
}
}
}

