/**
 * TextMagic API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * Contact: support@textmagi.biz
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.8.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * GetMessagePriceResponse.h
 *
 * 
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_GetMessagePriceResponse_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_GetMessagePriceResponse_H_


#include "../ModelBase.h"

#include "Object.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  GetMessagePriceResponse
    : public ModelBase
{
public:
    GetMessagePriceResponse();
    virtual ~GetMessagePriceResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// GetMessagePriceResponse members

    /// <summary>
    /// 
    /// </summary>
    double getTotal() const;
        void setTotal(double value);
    /// <summary>
    /// 
    /// </summary>
    int32_t getParts() const;
        void setParts(int32_t value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Object> getCountries() const;
        void setCountries(std::shared_ptr<Object> value);

protected:
    double m_Total;
        int32_t m_Parts;
        std::shared_ptr<Object> m_Countries;
    };

}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_GetMessagePriceResponse_H_ */
