/**
 * TextMagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.8.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * GetSenderSettingsResponse.h
 *
 * 
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_GetSenderSettingsResponse_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_GetSenderSettingsResponse_H_


#include "../ModelBase.h"

#include "Object.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  GetSenderSettingsResponse
    : public ModelBase
{
public:
    GetSenderSettingsResponse();
    virtual ~GetSenderSettingsResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// GetSenderSettingsResponse members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Object> getUser() const;
        void setUser(std::shared_ptr<Object> value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Object> getSpecial() const;
        void setSpecial(std::shared_ptr<Object> value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Object> getOther() const;
        void setOther(std::shared_ptr<Object> value);

protected:
    std::shared_ptr<Object> m_User;
        std::shared_ptr<Object> m_Special;
        std::shared_ptr<Object> m_Other;
    };

}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_GetSenderSettingsResponse_H_ */
