/**
 * TextMagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.8.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "ImportColumnMappingItem.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

ImportColumnMappingItem::ImportColumnMappingItem()
{
    m_ColumnPositionInFile = utility::conversions::to_string_t("");
    m_FieldOrCustomFieldId = utility::conversions::to_string_t("");
}

ImportColumnMappingItem::~ImportColumnMappingItem()
{
}

void ImportColumnMappingItem::validate()
{
    // TODO: implement validation
}

web::json::value ImportColumnMappingItem::toJson() const
{
    web::json::value val = web::json::value::object();

    val[utility::conversions::to_string_t("columnPositionInFile")] = ModelBase::toJson(m_ColumnPositionInFile);
    val[utility::conversions::to_string_t("fieldOrCustomFieldId")] = ModelBase::toJson(m_FieldOrCustomFieldId);

    return val;
}

void ImportColumnMappingItem::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("columnPositionInFile")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("columnPositionInFile")];
        if(!fieldValue.is_null())
        {
            setColumnPositionInFile(ModelBase::stringFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("fieldOrCustomFieldId")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("fieldOrCustomFieldId")];
        if(!fieldValue.is_null())
        {
            setFieldOrCustomFieldId(ModelBase::stringFromJson(fieldValue));
        }
    }
}

void ImportColumnMappingItem::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("columnPositionInFile"), m_ColumnPositionInFile));
    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("fieldOrCustomFieldId"), m_FieldOrCustomFieldId));
}

void ImportColumnMappingItem::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    setColumnPositionInFile(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("columnPositionInFile"))));
    setFieldOrCustomFieldId(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("fieldOrCustomFieldId"))));
}

utility::string_t ImportColumnMappingItem::getColumnPositionInFile() const
{
    return m_ColumnPositionInFile;
}


void ImportColumnMappingItem::setColumnPositionInFile(utility::string_t value)
{
    m_ColumnPositionInFile = value;
    
}
utility::string_t ImportColumnMappingItem::getFieldOrCustomFieldId() const
{
    return m_FieldOrCustomFieldId;
}


void ImportColumnMappingItem::setFieldOrCustomFieldId(utility::string_t value)
{
    m_FieldOrCustomFieldId = value;
    
}
}
}
}
}

