/**
 * TextMagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.8.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * UpdateSurveyNodeInputObject.h
 *
 * 
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_UpdateSurveyNodeInputObject_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_UpdateSurveyNodeInputObject_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace com {
namespace textmagic {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  UpdateSurveyNodeInputObject
    : public ModelBase
{
public:
    UpdateSurveyNodeInputObject();
    virtual ~UpdateSurveyNodeInputObject();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// UpdateSurveyNodeInputObject members

    /// <summary>
    /// Node label
    /// </summary>
    utility::string_t getLabel() const;
    bool labelIsSet() const;
    void unsetLabel();
    void setLabel(utility::string_t value);
    /// <summary>
    /// Define node is ending for survey. Default is false
    /// </summary>
    bool isIsEndNode() const;
    bool isEndNodeIsSet() const;
    void unsetIsEndNode();
    void setIsEndNode(bool value);
    /// <summary>
    /// Node body
    /// </summary>
    utility::string_t getBody() const;
    bool bodyIsSet() const;
    void unsetBody();
    void setBody(utility::string_t value);
    /// <summary>
    /// Define delay for sending question to recipients after previous answer.
    /// </summary>
    int32_t getSendDelay() const;
    bool sendDelayIsSet() const;
    void unsetSendDelay();
    void setSendDelay(int32_t value);

protected:
    utility::string_t m_Label;
    bool m_LabelIsSet;
    bool m_IsEndNode;
    bool m_IsEndNodeIsSet;
    utility::string_t m_Body;
    bool m_BodyIsSet;
    int32_t m_SendDelay;
    bool m_SendDelayIsSet;
};

}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_UpdateSurveyNodeInputObject_H_ */
