/**
 * TextMagic API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * Contact: support@textmagi.biz
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.8.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * UploadMessageAttachmentResponse.h
 *
 * 
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_UploadMessageAttachmentResponse_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_UploadMessageAttachmentResponse_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace com {
namespace textmagic {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  UploadMessageAttachmentResponse
    : public ModelBase
{
public:
    UploadMessageAttachmentResponse();
    virtual ~UploadMessageAttachmentResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// UploadMessageAttachmentResponse members

    /// <summary>
    /// 
    /// </summary>
    int32_t getChars() const;
        void setChars(int32_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getHref() const;
        void setHref(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getName() const;
        void setName(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    int32_t getSize() const;
        void setSize(int32_t value);

protected:
    int32_t m_Chars;
        utility::string_t m_Href;
        utility::string_t m_Name;
        int32_t m_Size;
    };

}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_UploadMessageAttachmentResponse_H_ */
